config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'main#home'
  #======================== ASK ================================
  # get 'home/index'
  get 'asks/recibidas'
  get 'asks/creadas'
  get 'asks/edit'
  patch 'asks/update', to: 'asks#update', as: 'asks_update'
  get 'asks/show'
  #  get 'asks/new'
  #  post 'asks', to: 'asks#create'
  get 'asks/delete', to: 'asks#delete', as: 'asks_delete'
  resources :asks do
    member do
      post 'aceptado'
      delete 'rechazado'
    end
  end
  #======================= CARS/ASK, CARS/REVIEWS ===================
  resources :cars do
    resources :reviews, only: [:new, :create]
    resources :asks, only: [:new, :create]
  end
  #====================== MENSAJE ====================================
  resources :conversaciones do
    resources :mensajes
  end
  #===================== USER ========================================
  devise_for :user, controllers: {
    registrations: 'users/registrations'
    }
  
  #====================== COMENTARIO ======================================
  resources :comentarios

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
    end
  end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ask.rb
# frozen_string_literal: true

class Ask < ApplicationRecord
  belongs_to :car
  has_and_belongs_to_many :asks

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :name, presence: true
  # validates :mail, presence: true
  # validates :reason, presence: true
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  has_many :reviews
  has_many :asks
  belongs_to :user

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :marca, presence: true
  # validates :modelo, presence: true
  # validates :año, presence: true, numericality: { only_integer: true }
  # validates :precio, presence: true, numericality: { only_integer: true }
  # validates :dueño, presence: true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
end

app/models/mensaje.rb
class Mensaje < ApplicationRecord
  # validates :contenido, presence: true
  # validates :car_id, presence: true, numericality: { only_integer: true }
  # validates :contenido, presence: true

  belongs_to :user
  belongs_to :car
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :user
  belongs_to :car

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :calificacion, presence: true, numericality: { only_integer: true }
  # validates :contenido, presence: true,length: { maximum: 100 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  acts_as_messageable
  enum role: [:Proveedor, :Restaurant]
  after_initialize :set_default_role, :if => :new_record?


  def set_default_role
    self.role ||= :Proveedor
  end
  

  def mailboxer_email(object)
    nil
  end
  
  has_many :reviews
  has_many :cars
  has_and_belongs_to_many :asks

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: Devise.email_regexp }
end

app/controllers/asks_controller.rb
# frozen_string_literal: true

class AsksController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
  end

  def create
    @car = Car.find(params[:car_id])
    @asks_params = params.require(:ask).permit(:name, :mail, :dates, :reason)
    @ask = Ask.create(@asks_params)
    @ask.user_id = current_user.id
    @ask.car_id = @car.id
    @ask.id_dueño = @car.user_id
    @ask.estado = 'PENDIENTE'
    if @ask.save
      redirect_to asks_creadas_path, notice: 'Se ha creado la solicitud correctamente'
    else
      redirect_to main_home_path, notice: 'Error al crear solicitud'
    end
  end

  def show
    @ask = Ask.find(params[:id])
  end

  def recibidas
    @owner_cars = user_signed_in? ? Car.where(user_id: current_user.id).all : []
    @cars_ids = []
    @owner_cars.each do |car|
      @cars_ids << car.id
    end
    @owner_asks = Ask.where(car_id: @cars_ids).all
  end

  def creadas
    @user_asks = Ask.where(user_id: current_user.id)
  end

  def edit
    @ask = Ask.find(params[:id])
  end

  def update
    @ask = Ask.find(params[:id])
    @asks_new_params = params.require(:ask).permit(:name, :mail, :dates, :reason)

    if @ask.update(@asks_new_params)
      redirect_to asks_creadas_path, notice: 'Se ha actualizado la información de la solicitud'
    else
      redirect_to asks_creadas_path, notice: 'Error al actualizar la información de la solicitud'
    end
  end

  def delete
    @ask = Ask.find(params[:id])
    @ask.delete
    redirect_to asks_recibidas_path, notice: 'Se ha eliminado la solicitud'
  end

  def aceptado
    @ask = Ask.find(params[:id])
    @ask.estado = 'ACEPTADO'
    current_user.asks << @ask
    redirect_to asks_recibidas_path, notice: 'Se ha aceptado la solicitud'
  end

  def rechazado
    @ask = Ask.find(params[:id])
    @ask.estado = 'RECHAZADO'
    current_user.asks << @ask
    redirect_to asks_recibidas_path, notice: 'Se ha rechazado la solicitud'
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController

  def index
    @car = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car_params = params.require(:car).permit(:marca, :modelo, :año, :precio, :dueño)
    @car = Car.create(@car_params)
    @car.user_id = current_user.id
    puts @car.user_id
    if @car.save
      redirect_to cars_path, notice: 'Se ha agregado el ingrediente a la base de datos'
    else
      redirect_to root_path, notice: 'Error al agregar el ingrediente'
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @new_car_params = params.require(:car).permit(:marca, :modelo, :año, :precio, :dueño)

    if @car.update(@new_car_params)
      redirect_to cars_path, notice: 'Se ha actualizado la información del ingrediente'
    else
      redirect_to cars_path, notice: 'Error al actualizar la información del ingrediente'
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.delete
    redirect_to cars_path, notice: 'Se ha eliminado la publicación'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def home; end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @car = Car.find(params[:car_id])
  end

  def create
    @car = Car.find(params[:car_id])
    @review_params = params.require(:review).permit(:contenido, :calificacion)
    @review = Review.create(@review_params)
    @review.user_id = current_user.id
    @review.car = @car
    if @review.save
      redirect_to car_path(@car.id), notice: 'Gracias por agregar una reseña'
    else
      redirect_to car_path(@car.id), notice: 'No se ha podido agregar la reseña'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/asks_helper.rb
# frozen_string_literal: true

module AsksHelper
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/helpers/comentario_helper.rb
# frozen_string_literal: true

module ComentarioHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/conversaciones_helper.rb
# frozen_string_literal: true

module ConversacionesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/helpers/mensajes_helper.rb
# frozen_string_literal: true

module MensajesHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/home/index.html.erb
<h1 align='center'>Hello World</h1>

app/views/main/home.html.erb
<head>
  <meta charset="UTF-8">
  <title>Landing Page</title>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>
<body class="letra">
  <header class="hero">
    <div class="textos-hero">
      <h1>Bienvenido a Proveedores UC</h1>
      <p>Creamos el mejor portal de proveedores para tu restaurant</p>
      <a href="#servicios">Nuestros Servicios</a>
    </div>
    <div class="svg-hero" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>
  </header>
  <section class="wave-contenedor website">
    <img src="<%= asset_path 'mockup.png' %>">
    <div class="contenedor-textos-main">
      <h2 class="titulo left">Esta es TÚ oportunidad. Todos los ingredientes que necesitas a tan solo 3 clics de distancia.</h2>
    </div>
  </section>
  <section class="info">
    <div class="contenedor">
      <h2 class="titulo left"></h2>
      <p></p>
    </div>
  </section>
  <section id="servicios" class="cards contenedor">
    <h2 class="titulo">Nuestros Servicios</h2>
    <div class="content-cards">

      <% if (not current_user or current_user.admin == true or current_user.role == 'Proveedor') %>
      <article class="card">
        <i class="fa-solid fa-arrow-up-from-bracket"></i>
        <h3>Publicar Ingredientes</h3>
        <% if current_user %>
          <% if (current_user.role == 'Proveedor' or current_user.admin == true) %>
            <p> <%= link_to "Hacer Publicación", new_car_path, class: "cta" %> </p>
          <% else %>
            <p> <%= link_to "Hacer Publicación", root_path, class: "cta" %> </p>
          <% end %>
        
        <% else %>
          <p> <%= link_to "Hacer Publicación", new_user_session_path, class: "cta" %> </p>
        <% end %>
      </article>
      <% end %>

      <article class="card">
        <i class="fa-solid fa-cutlery"></i>
        <h3>Ver Ingredientes</h3>
        <p> <%= link_to "Ver Ingredientes", cars_path, class: "cta" %> </p>
      </article>
      
      <article class="card">
        <i class="fa-solid fa-inbox"></i>
        <h3>Ver solicitudes</h3>
        <% if current_user %>
          <% if (current_user.role == 'Proveedor' or current_user.admin == true) %>
            <p> <%= link_to "Revisar solicitudes recibidas", "asks/recibidas", class: "cta" %> </p>
           <% end %>
          <% if (current_user.role == 'Restaurant' or current_user.admin == true) %>
            <p> <%= link_to "Revisar estado de mis solicitudes", asks_creadas_path, class: "cta" %> </p>
          <% end %>
        
        <% else %>
          <p> <%= link_to "Revisar mis solicitudes", new_user_session_path, class: "cta" %> </p>
        <% end %>
      </article>
      
      <article class="card">
        <i class="fa-regular fa-message"></i>
        <h3>Chats</h3>
        <% if current_user %>
          <p> <%= link_to "Ver Mensajes", conversaciones_path, class: "cta" %> </p>
        <% else %>
          <p> <%= link_to "Ver Mensajes", new_user_session_path, class: "cta" %> </p>
        <% end %>
      </article>
    </div>
  </section>
  <div class="svg-wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #7FB77E;"></path></svg></div>
  <section class="info">
    <div class="contenedor">
        <h2 class="titulo left"></h2>
        <p class="parrafo"></p>
        <a href="#" class="cta">Volver al inicio</a>
    </div>
    
  </section>
  <footer id="contacto">
  </footer>
  <script src="https://kit.fontawesome.com/c497ad14fd.js" crossorigin="anonymous"></script>
</body>

app/views/reviews/new.html.erb
<head>
  <link rel="stylesheet" href="register_style.css">
  <script src="https://kit.fontawesome.com/c497ad14fd.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>
<body class="letra">
 <div class="formulario">
 <br>
 <h2 align="center">Escribe una reseña</h2>
<%= form_with model: [@car, Review.new] do |f| %>
    <div class="username">
      <%= f.text_field :contenido %> 
      <label>Contenido&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>
    <div class="username">
      <%= f.text_field :clasificacion %>     
      <label>Clasificacion&nbsp;&nbsp;<i class="fa-regular"></i></label>  
    </div>
    <div>
        <%= f.submit %>
    </div>
    <br>
<% end %>
  </div>
</body>