config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'main#home'
  #======================== ASK ================================
  # get 'home/index'
  get 'asks/recibidas'
  get 'asks/creadas'
  get 'asks/edit'
  patch 'asks/update', to: 'asks#update', as: 'asks_update'
  get 'asks/show'
  #  get 'asks/new'
  #  post 'asks', to: 'asks#create'
  get 'asks/delete', to: 'asks#delete', as: 'asks_delete'
  resources :asks do
    member do
      post 'aceptado'
      delete 'rechazado'
    end
  end
  #======================= CARS/ASK, CARS/REVIEWS ===================
  resources :cars do
    resources :reviews, only: [:new, :create]
    resources :asks, only: [:new, :create]
  end
  #====================== MENSAJE ====================================
  resources :conversaciones do
    resources :mensajes
  end
  #===================== USER ========================================
  devise_for :user, controllers: {
    registrations: 'users/registrations'
    }
  
  #====================== COMENTARIO ======================================
  resources :comentarios

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
    end
  end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ask.rb
# frozen_string_literal: true

class Ask < ApplicationRecord
  belongs_to :car
  has_and_belongs_to_many :asks

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :name, presence: true
  # validates :mail, presence: true
  # validates :reason, presence: true
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  has_many :reviews
  has_many :asks
  belongs_to :user

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :marca, presence: true
  # validates :modelo, presence: true
  # validates :año, presence: true, numericality: { only_integer: true }
  # validates :precio, presence: true, numericality: { only_integer: true }
  # validates :dueño, presence: true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
end

app/models/mensaje.rb
class Mensaje < ApplicationRecord
  # validates :contenido, presence: true
  # validates :car_id, presence: true, numericality: { only_integer: true }
  # validates :contenido, presence: true

  belongs_to :user
  belongs_to :car
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :user
  belongs_to :car

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :calificacion, presence: true, numericality: { only_integer: true }
  # validates :contenido, presence: true,length: { maximum: 100 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  acts_as_messageable
  enum role: [:Proveedor, :Restaurant]
  after_initialize :set_default_role, :if => :new_record?


  def set_default_role
    self.role ||= :Proveedor
  end
  

  def mailboxer_email(object)
    nil
  end
  
  has_many :reviews
  has_many :cars
  has_and_belongs_to_many :asks

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: Devise.email_regexp }
end

app/controllers/asks_controller.rb
# frozen_string_literal: true

class AsksController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
  end

  def create
    @car = Car.find(params[:car_id])
    @asks_params = params.require(:ask).permit(:name, :mail, :dates, :reason)
    @ask = Ask.create(@asks_params)
    @ask.user_id = current_user.id
    @ask.car_id = @car.id
    @ask.id_dueño = @car.user_id
    @ask.estado = 'PENDIENTE'
    if @ask.save
      redirect_to asks_creadas_path, notice: 'Se ha creado la solicitud correctamente'
    else
      redirect_to main_home_path, notice: 'Error al crear solicitud'
    end
  end

  def show
    @ask = Ask.find(params[:id])
  end

  def recibidas
    @owner_cars = user_signed_in? ? Car.where(user_id: current_user.id).all : []
    @cars_ids = []
    @owner_cars.each do |car|
      @cars_ids << car.id
    end
    @owner_asks = Ask.where(car_id: @cars_ids).all
  end

  def creadas
    @user_asks = Ask.where(user_id: current_user.id)
  end

  def edit
    @ask = Ask.find(params[:id])
  end

  def update
    @ask = Ask.find(params[:id])
    @asks_new_params = params.require(:ask).permit(:name, :mail, :dates, :reason)

    if @ask.update(@asks_new_params)
      redirect_to asks_creadas_path, notice: 'Se ha actualizado la información de la solicitud'
    else
      redirect_to asks_creadas_path, notice: 'Error al actualizar la información de la solicitud'
    end
  end

  def delete
    @ask = Ask.find(params[:id])
    @ask.delete
    redirect_to asks_recibidas_path, notice: 'Se ha eliminado la solicitud'
  end

  def aceptado
    @ask = Ask.find(params[:id])
    @ask.estado = 'ACEPTADO'
    current_user.asks << @ask
    redirect_to asks_recibidas_path, notice: 'Se ha aceptado la solicitud'
  end

  def rechazado
    @ask = Ask.find(params[:id])
    @ask.estado = 'RECHAZADO'
    current_user.asks << @ask
    redirect_to asks_recibidas_path, notice: 'Se ha rechazado la solicitud'
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController

  def index
    @car = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car_params = params.require(:car).permit(:marca, :modelo, :año, :precio, :dueño)
    @car = Car.create(@car_params)
    @car.user_id = current_user.id
    puts @car.user_id
    if @car.save
      redirect_to cars_path, notice: 'Se ha agregado el ingrediente a la base de datos'
    else
      redirect_to root_path, notice: 'Error al agregar el ingrediente'
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @new_car_params = params.require(:car).permit(:marca, :modelo, :año, :precio, :dueño)

    if @car.update(@new_car_params)
      redirect_to cars_path, notice: 'Se ha actualizado la información del ingrediente'
    else
      redirect_to cars_path, notice: 'Error al actualizar la información del ingrediente'
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.delete
    redirect_to cars_path, notice: 'Se ha eliminado la publicación'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def home; end
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  before_action :set_conversation

  def create
    receipt = current_user.reply_to_conversation(@conversacion, params[:body])
    redirect_to conversacione_path(receipt.conversation)
  end
  
  private

    def set_conversation
      @conversacion = current_user.mailbox.conversations.find(params[:conversacione_id])
    end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @car = Car.find(params[:car_id])
  end

  def create
    @car = Car.find(params[:car_id])
    @review_params = params.require(:review).permit(:contenido, :calificacion)
    @review = Review.create(@review_params)
    @review.user_id = current_user.id
    @review.car = @car
    if @review.save
      redirect_to car_path(@car.id), notice: 'Gracias por agregar una reseña'
    else
      redirect_to car_path(@car.id), notice: 'No se ha podido agregar la reseña'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/asks_helper.rb
# frozen_string_literal: true

module AsksHelper
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/helpers/comentario_helper.rb
# frozen_string_literal: true

module ComentarioHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/conversaciones_helper.rb
# frozen_string_literal: true

module ConversacionesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/helpers/mensajes_helper.rb
# frozen_string_literal: true

module MensajesHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/asks/creadas.html.erb
<h1 align='center'>Solicitudes Creadas</h1><br>

<% notice %>
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Ingredientes</th>
      <th>Ubicación</th>
      <th>Restaurante</th>
      <th>Despacho</th>
      <th>Cantidad de kg por despacho</th>
      <th>Intervalo de días de despacho</th>
      <th>Estado</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% if current_user.admin == false %>
      <% @user_asks.each do |ask| %>
      <tr>
        <th scope="row"><%= ask.car.marca %></th>
        <td><%= ask.car.modelo %></td>
        <td><%= ask.name %></td>
        <td><%= ask.mail %></td>
        <td><%= ask.dates %> kg</td>
        <td><%= ask.reason %> días</td>
        <% if ask.estado == 'PENDIENTE' %>
          <td><span class="badge text-bg-warning"><%= ask.estado %></span></td>
          <td><%= link_to "Editar", asks_edit_path(:id => ask.id) %></td>
          <td><%= link_to "Eliminar", asks_delete_path(:id => ask.id), method: :get %></td>
        <% elsif ask.estado == 'RECHAZADO' %>
          <td><span class="badge text-bg-danger"><%= ask.estado %></span></td>
          <td><%= link_to "Editar", asks_edit_path(:id => ask.id) %></td>
          <td><%= link_to "Eliminar", asks_delete_path(:id => ask.id), method: :get %></td>
        <% else %>
          <td><span class="badge text-bg-success"><%= ask.estado %></span></td>
          <td><%= link_to 'Iniciar conversación', new_conversacione_path %></td>
        <% end %>
      </tr>
      <% end %>
    <% else %>
      <% Ask.all.each do |ask| %>
      <tr>
        <th scope="row"><%= ask.car.marca + " " + ask.car.modelo %></th>
        <td><%= ask.car.año %></td>
        <td><%= ask.name %></td>
        <td><%= ask.mail %></td>
        <td><%= ask.dates %></td>
        <td><%= ask.reason %></td>
        <% if ask.estado == 'PENDIENTE' %>
          <td><span class="badge text-bg-warning"><%= ask.estado %></span></td>
          <td><%= link_to "Editar", asks_edit_path(:id => ask.id) %></td>
          <td><%= link_to "Eliminar", asks_delete_path(:id => ask.id), method: :get %></td>
        <% elsif ask.estado == 'RECHAZADO' %>
          <td><span class="badge text-bg-danger"><%= ask.estado %></span></td>
          <td><%= link_to "Editar", asks_edit_path(:id => ask.id) %></td>
          <td><%= link_to "Eliminar", asks_delete_path(:id => ask.id), method: :get %></td>
        <% else %>
          <td><span class="badge text-bg-success"><%= ask.estado %></span></td>
          <td><%= link_to 'Iniciar conversación', new_conversacione_path %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
</div>
<div class="position-absolute bottom-0 start-50 translate-middle-x">
<%= button_to "Volver", root_path, :class => "btn btn-outline-secondary", :method => :get %>
<br><br><br>
</div>

app/views/asks/edit.html.erb
<head>
  <link rel="stylesheet" href="register_style.css">
  <script src="https://kit.fontawesome.com/c497ad14fd.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>
<body class="letra">
<div class="formulario">
<br>
<h2 align="center">Editar Solicitud</h2>
<% car = Car.find(@ask.car.id) %>
<h2 align="center"><%= car.marca %></h2>

<%= form_with( model: @ask, method: :patch, url: asks_update_path(:id => @ask.id)) do |c| %>

<div class="username">
    <%= c.text_field :name %>
    <label>Nombre Restaurant&nbsp;&nbsp;<i class="fa-regular"></i></label>
</div>
<div class="username">
    <%= c.text_field :mail %>
    <label>Dirección despacho&nbsp;&nbsp;<i class="fa-regular"></i></label>
</div>
<div class="username">
    <%= c.text_field :dates %>
    <label>Cantidad de kg por despacho&nbsp;&nbsp;<i class="fa-regular"></i></label>
</div>
<div class="username">
    <%= c.text_field :reason %>
    <label>Intervalo de días de despacho&nbsp;&nbsp;<i class="fa-regular"></i></label>
</div>
<div class="username">
    <%= c.submit 'Editar Solicitud' %>
</div>
<% end %>

app/views/asks/new.html.erb
<head>
  <link rel="stylesheet" href="register_style.css">
  <script src="https://kit.fontawesome.com/c497ad14fd.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>
<body class="letra">
<div class="formulario">
<br>
<h2 align='center'>Crear Solicitud:</h2>
<h2 align='center'><%= @car.marca %></h2>

<%= form_with model: [@car, Ask.new] do |c| %>
    <div class="username">
      <%= c.text_field :name %>
      <label>Nombre Restaurant&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>
    <div class="username">
      <%= c.text_field :mail %>
      <label>Dirección despacho&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>
    <div class="username">
        <%= c.text_field :dates %>
        <label>Cantidad de kg por despacho&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>
    <div class="username">
        <%= c.text_field :reason %>
        <label>Intervalo de días de despacho&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>
    <div class="username">
      <%= c.submit 'Hacer Solicitud' %>
    </div>
    <br>
<% end %>
</div>
</body>

app/views/asks/recibidas.html.erb
<h1 align='center'>Solicitudes Recibidas</h1><br>

<% notice %>
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Auto</th>
      <th>Año</th>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Fechas del Arriendo</th>
      <th>Motivo del Arriendo</th>
      <th>Estado</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% if current_user.admin == false %>
      <% @owner_asks.each do |ask| %>
      <tr>
        <th scope="row"><%= ask.car.marca + " " + ask.car.modelo %></th>
        <td><%= ask.car.año %></td>
        <td><%= ask.name %></td>
        <td><%= ask.mail %></td>
        <td><%= ask.dates %></td>
        <td><%= ask.reason %></td>
        <td><%= link_to "Ver solicitud", ask_path(:id => ask.id) %></td>
      </tr>
      <% end %>
    <% else %>
      <% Ask.all.each do |ask| %>
      <tr>
        <th scope="row"><%= ask.car.marca + " " + ask.car.modelo %></th>
        <td><%= ask.car.año %></td>
        <td><%= ask.name %></td>
        <td><%= ask.mail %></td>
        <td><%= ask.dates %></td>
        <td><%= ask.reason %></td>
        <td><%= link_to "Ver solicitud", ask_path(:id => ask.id) %></td>
        <% if ask.estado == 'ACEPTADO' %>
          <td><%= link_to 'Finalizar arriendo', new_comentario_path %></td>
        <% end %>
      </tr>
      
      <% end %>
    <% end %>

</div>
<div class="position-absolute bottom-0 start-50 translate-middle-x">
<%= button_to "Volver", root_path, :class => "btn btn-outline-secondary", :method => :get %>
<br><br><br>
</div>

app/views/asks/show.html.erb
<div class="container">
<table class="table">
  <tbody class="table-group-divider">
    <tr>
    <th>Nombre Restaurant:</th>
    <td><%= @ask.name %></td>
  </tr>
    <tr>
    <th>Dirección despacho:</th>
    <td><%= @ask.mail %></td>
  </tr>

  <tr>
    <th>Cantidad de kg por despacho:</th>
    <td><%= @ask.dates %> kg</td>
  </tr>

  <tr>
    <th>Intervalo de días de despacho:</th>
    <td><%= @ask.reason %> días</td>
  </tr>
</table>

    <% if current_user.asks.ids.include? @ask.id %>
      <table class="table">
        <tbody class="table-group-divider">
        <tr>
          <th>Estado:</th>
          <% if @ask.estado == 'PENDIENTE' %>
          <td><span class="badge text-bg-warning"><%= @ask.estado %></span></td>
        <% elsif @ask.estado == 'RECHAZADO' %>
          <td><span class="badge text-bg-danger"><%= @ask.estado %></span></td>
        <% else %>
          <td><span class="badge text-bg-success"><%= @ask.estado %></span></td>
        <% end %>
        <tr>
          <% if @ask.estado == 'ACEPTADO' %>
        </tr>
          <td><%= link_to "Iniciar Conversacion", new_conversacione_path %></td>
        <% end %>
      </table>
    <% else %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= button_to "Aceptar Solicitud", aceptado_ask_path(@ask), :class =>"btn btn-outline-success",method: :post %>
        <%= button_to "Rechazar Solicitud", rechazado_ask_path(@ask), :class =>"btn btn-outline-danger", method: :delete %>
    </div>    
    <% end %>
  </div>
  

app/views/cars/edit.html.erb
<head>
  <link rel="stylesheet" href="register_style.css">
  <script src="https://kit.fontawesome.com/c497ad14fd.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>
<body class="letra">
<div class="formulario">
<br>
<h2 align="center">Editar Publicación</h2>

<%= form_with( model: @car, method: :patch) do |c| %>

    <div class="username">
      <%= c.text_field :marca %>
      <label>Marca&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>

    <div class="username">
      <%= c.text_field :modelo %>
      <label>Modelo&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>

    <div class="username">
      <%= c.text_field :año %>
      <label>Año&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>

    <div class="username">
      <%= c.text_field :precio %>
      <label>Precio&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>

    <div class="username">
      <%= c.text_field :dueño %>
      <label>Dueño&nbsp;&nbsp;<i class="fa-regular"></i></label>
    </div>

    <div class="username">
      <%= c.submit 'Guardar' %>
    </div>
<% end %>
</div>
</body>

app/views/cars/index.html.erb
<h1 align='center' class="letra">Ingredientes</h1>

<% notice %>
<br>

<head>
  <meta charset="UTF-8">
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>
<body>
<div class="row row-cols-1 row-cols-md-5 g-4">
  <% @car.each do |car| %>
  <div class="col">
    <div class="card h-100">
      <% if car.marca.downcase.include? "ajo" %>
        <img src="<%= asset_path 'ajo.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "atun" %>
        <img src="<%= asset_path 'atun.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "brocoli" %>
        <img src="<%= asset_path 'brocoli.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "cebolla" %>
        <img src="<%= asset_path 'cebolla.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "huevo" %>
        <img src="<%= asset_path 'huevo.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "lechuga" %>
        <img src="<%= asset_path 'lechuga.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "limon" %>
        <img src="<%= asset_path 'limon.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "palta" %>
        <img src="<%= asset_path 'palta.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "pimenton" %>
        <img src="<%= asset_path 'pimenton.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "rabano" %>
        <img src="<%= asset_path 'rabano.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "salmon" %>
        <img src="<%= asset_path 'salmon.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "tomate" %>
        <img src="<%= asset_path 'tomate.png' %>" class="card-img-top" width="50" height="auto">
      <% elsif car.marca.downcase.include? "zanahoria" %>
        <img src="<%= asset_path 'zanahoria.png' %>" class="card-img-top" width="50" height="auto">
      <% else %>
        <img src="<%= asset_path 'default.png' %>" class="card-img-top" width="50" height="auto">
      <% end %>
      <div class="card-body">
        <% if user_signed_in?%>
          <% if car.user_id == current_user.id %>
            <h5 class="card-title"> <span class="badge bg-success">Tu Publicación</span> <br><br><%= car.marca %> </h5>
          <% else %>
            <h5 class="card-title"> <br><%= car.marca %> </h5>
          <% end %>
        <% else %>
          <h5 class="card-title"> <br><%= car.marca %> </h5>
        <% end %>
        <p class="card-text">Ubicación: <%= car.modelo %></p>
        <p class="card-text">Precio por kg: $<%= car.precio %></p>
        <p class="card-text">Cantidad disponible (kg): <%= car.año %></p>
        <% if current_user %>
          <p> <%= link_to "Detalles", car_path(car), class: "cta" %> </p>
        <% else %>
          <p> <%= link_to "Detalles", user_session_path, class: "cta" %> </p>
        <% end %>
        <p class="card-text"><small class="text-muted">Actualizado en: <%= car.updated_at.strftime('%d/%m/%Y %I:%M') %></small></p>
      </div>
    </div>
  </div>
  <% end %>
</div>
</body>

app/views/cars/new.html.erb
<head>
  <link rel="stylesheet" href="register_style.css">
  <script src="https://kit.fontawesome.com/c497ad14fd.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>

<body class="letra">
  <div class="formulario">
    <br>
    <h2 align="center">Publicar un ingrediente</h2>

    <%= form_with(model: @car, method: :post) do |c| %>
        <div class="username">
          <%= c.text_field :marca %>
          <label>Ingrediente</label>
        </div>
        <div class="username">
          <%= c.text_field :modelo %>
          <label>Ubicación (Localidad / Comuna)</label>
        </div>
        <div class="username">
          <%= c.text_field :año %>
          <label>Cantidad disponible (kg)</label>
        </div>
        <div class="username">
          <%= c.text_field :precio %>
          <label>Precio por kg</label>
        </div>
        <div class="username">
          <%= c.text_field :dueño %>
          <label>Nombre Proveedor</label>
        </div>
        <div class="actions">
          <%= c.submit 'Hacer Publicacion' %>
        </div>
        <br>
    <% end %>
  </div>
</body>

app/views/cars/show.html.erb
<div class="container">
<h1 align='center'><%= @car.marca %></h1>
<br><br><br>

<div class="position-absolute top-50 start-50 translate-middle">
<div class="card" style="width: 40rem;">
  <div class="card-header">
    <%= @car.marca %>
  </div>
  <div class="card-body">
    <p class="card-text"> Ingrediente: <%= @car.marca %> </p>
    <p class="card-text"> Ubicación: <%= @car.modelo %> </p>
    <p class="card-text"> Cantidad: <%= @car.año %> </p>
    <p class="card-text"> Precio: <%= @car.precio %> </p>
    <p class="card-text"> Nombre Proveedor: <%= @car.dueño %> </p>
  </div>
  <div class="card-footer text-muted">
    <p class="card-text"><small class="text-muted">Creado en: <%= @car.created_at.strftime('%d/%m/%Y %I:%M') %></small></p>
    <p class="card-text"><small class="text-muted">Actualizado en: <%= @car.updated_at.strftime('%d/%m/%Y %I:%M') %></small></p>
    <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
      <div class="btn-group dropdown-center"  role="group">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Acciones
        </button>
        <ul class="dropdown-menu">
        <% if (@car.user_id == current_user.id or current_user.admin == true)%>
          <%= button_to "Editar", edit_car_path(:id => @car.id), :class => "dropdown-item", :method => :get %>
        <% end %>
        <% if ((@car.user_id != current_user.id and current_user.role == "Restaurant") or current_user.admin == true)%>
          <%= button_to "Hacer Solicitud", new_car_ask_path(@car), :class => "dropdown-item", :method => :get %>
        <% end %>
        <% if (@car.user_id == current_user.id or current_user.admin == true)%>
          <%= button_to "Eliminar", car_path(:id => @car.id), :class => "dropdown-item", :method => :get %>
        <% end %>
        </ul>
      </div>
      <div class="btn-group dropdown-center"  role="group">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Reseñas
        </button>
        <ul class="dropdown-menu">
        <% if ((current_user.role == "Proveedor" and @car.user_id != current_user.id) or current_user.admin == true )%>
          <%= button_to "Crear reseña", new_car_review_path(@car), :class => "dropdown-item", :method => :get %>
        <% end %>
        <li><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#Resenas">Leer reseñas</button></li>
        </ul>
      </div>
    </div>
    </div>
</div>

</div>

</div>

<div class="position-absolute bottom-0 start-50 translate-middle-x">
<%= button_to "Volver al menu", cars_path, :class => "btn btn-outline-secondary", :method => :get %>
<br><br><br>
</div>


<div class="modal fade modal-xl" id="Resenas" tabindex="-1" aria-hidden="true" style="">
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Reseñas</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <table class="table table-borderless">
      <thead>
      <tr>
      <th scope="col">Usuario</th>
      <th scope="col">Contenido</th>
      </tr>
      </thead>
      <tbody>
        <% @car.reviews.each do |review| %>
          <tr>
            <th scope="row"><%= review.user.name %></th>
            <td><%= review.contenido %></td>
          </tr>
        <% end %>
      </tbody>
      </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>