config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'main#home'
  #======================== ASK ================================
  # get 'home/index'
  get 'asks/recibidas'
  get 'asks/creadas'
  get 'asks/edit'
  patch 'asks/update', to: 'asks#update', as: 'asks_update'
  get 'asks/show'
  #  get 'asks/new'
  #  post 'asks', to: 'asks#create'
  get 'asks/delete', to: 'asks#delete', as: 'asks_delete'
  resources :asks do
    member do
      post 'aceptado'
      delete 'rechazado'
    end
  end
  #======================= CARS/ASK, CARS/REVIEWS ===================
  resources :cars do
    resources :reviews, only: [:new, :create]
    resources :asks, only: [:new, :create]
  end
  #====================== MENSAJE ====================================
  resources :conversaciones do
    resources :mensajes
  end
  #===================== USER ========================================
  devise_for :user, controllers: {
    registrations: 'users/registrations'
    }
  
  #====================== COMENTARIO ======================================
  resources :comentarios

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
    end
  end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ask.rb
# frozen_string_literal: true

class Ask < ApplicationRecord
  belongs_to :car
  has_and_belongs_to_many :asks

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :name, presence: true
  # validates :mail, presence: true
  # validates :reason, presence: true
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  has_many :reviews
  has_many :asks
  belongs_to :user

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :marca, presence: true
  # validates :modelo, presence: true
  # validates :año, presence: true, numericality: { only_integer: true }
  # validates :precio, presence: true, numericality: { only_integer: true }
  # validates :dueño, presence: true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
end

app/models/mensaje.rb
class Mensaje < ApplicationRecord
  # validates :contenido, presence: true
  # validates :car_id, presence: true, numericality: { only_integer: true }
  # validates :contenido, presence: true

  belongs_to :user
  belongs_to :car
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :user
  belongs_to :car

  # validates :id, presence: true, numericality: { only_integer: true }
  # validates :calificacion, presence: true, numericality: { only_integer: true }
  # validates :contenido, presence: true,length: { maximum: 100 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  acts_as_messageable
  enum role: [:Proveedor, :Restaurant]
  after_initialize :set_default_role, :if => :new_record?


  def set_default_role
    self.role ||= :Proveedor
  end
  

  def mailboxer_email(object)
    nil
  end
  
  has_many :reviews
  has_many :cars
  has_and_belongs_to_many :asks

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: Devise.email_regexp }
end

app/controllers/asks_controller.rb
# frozen_string_literal: true

class AsksController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
  end

  def create
    @car = Car.find(params[:car_id])
    @asks_params = params.require(:ask).permit(:name, :mail, :dates, :reason)
    @ask = Ask.create(@asks_params)
    @ask.user_id = current_user.id
    @ask.car_id = @car.id
    @ask.id_dueño = @car.user_id
    @ask.estado = 'PENDIENTE'
    if @ask.save
      redirect_to asks_creadas_path, notice: 'Se ha creado la solicitud correctamente'
    else
      redirect_to main_home_path, notice: 'Error al crear solicitud'
    end
  end

  def show
    @ask = Ask.find(params[:id])
  end

  def recibidas
    @owner_cars = user_signed_in? ? Car.where(user_id: current_user.id).all : []
    @cars_ids = []
    @owner_cars.each do |car|
      @cars_ids << car.id
    end
    @owner_asks = Ask.where(car_id: @cars_ids).all
  end

  def creadas
    @user_asks = Ask.where(user_id: current_user.id)
  end

  def edit
    @ask = Ask.find(params[:id])
  end

  def update
    @ask = Ask.find(params[:id])
    @asks_new_params = params.require(:ask).permit(:name, :mail, :dates, :reason)

    if @ask.update(@asks_new_params)
      redirect_to asks_creadas_path, notice: 'Se ha actualizado la información de la solicitud'
    else
      redirect_to asks_creadas_path, notice: 'Error al actualizar la información de la solicitud'
    end
  end

  def delete
    @ask = Ask.find(params[:id])
    @ask.delete
    redirect_to asks_recibidas_path, notice: 'Se ha eliminado la solicitud'
  end

  def aceptado
    @ask = Ask.find(params[:id])
    @ask.estado = 'ACEPTADO'
    current_user.asks << @ask
    redirect_to asks_recibidas_path, notice: 'Se ha aceptado la solicitud'
  end

  def rechazado
    @ask = Ask.find(params[:id])
    @ask.estado = 'RECHAZADO'
    current_user.asks << @ask
    redirect_to asks_recibidas_path, notice: 'Se ha rechazado la solicitud'
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController

  def index
    @car = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car_params = params.require(:car).permit(:marca, :modelo, :año, :precio, :dueño)
    @car = Car.create(@car_params)
    @car.user_id = current_user.id
    puts @car.user_id
    if @car.save
      redirect_to cars_path, notice: 'Se ha agregado el ingrediente a la base de datos'
    else
      redirect_to root_path, notice: 'Error al agregar el ingrediente'
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @new_car_params = params.require(:car).permit(:marca, :modelo, :año, :precio, :dueño)

    if @car.update(@new_car_params)
      redirect_to cars_path, notice: 'Se ha actualizado la información del ingrediente'
    else
      redirect_to cars_path, notice: 'Error al actualizar la información del ingrediente'
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.delete
    redirect_to cars_path, notice: 'Se ha eliminado la publicación'
  end
end

app/controllers/conversaciones_controller.rb
class ConversacionesController < ApplicationController
    def index
        @conversaciones = current_user.mailbox.conversations
    end

    def show
        @conversacion = current_user.mailbox.conversations.find(params[:id])
    end

    def new
        @usuarios = User.all - [current_user]
    end

    def create
        usuario = User.find(params[:user_id])
        enviar = current_user.send_message(usuario, params[:body], params[:subject])
        redirect_to conversacione_path(enviar.conversation)
    end

end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/asks_helper.rb
# frozen_string_literal: true

module AsksHelper
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/helpers/comentario_helper.rb
# frozen_string_literal: true

module ComentarioHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/conversaciones_helper.rb
# frozen_string_literal: true

module ConversacionesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/helpers/mensajes_helper.rb
# frozen_string_literal: true

module MensajesHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/conversaciones/index.html.erb
<head>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>
<body class="letra">
<section class="h-screen flex-col overflow-scroll">
  <h1 class="p-6"><strong>Todas las conversaciones</strong></h1>
  <div class="container text-center">
  <% @conversaciones.each do |conversacion| %>
  <div class="row">
  <div class="col">
  <%= link_to conversacione_path(conversacion), :action => 'go' do %>
  <div class="card">
    <div class="card-header">
      <img src="<%= asset_path 'usuarios.png' %>" class="rounded-full w-12 mr-4">
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <strong><%= conversacion.subject %></strong>
      </blockquote>
    </div>
  </div>
  <% end %>
  </div>
  </div>
  <% end %>
  </div>
  </section>
  <section align="center" class="p-6">
    <%= button_to "Nueva Conversacion", new_conversacione_path, :class => "btn btn-outline-secondary", :method => :get %>
  </section>
</body>

app/views/conversaciones/new.html.erb
<head>
    <link rel="stylesheet" href="register_style.css">
    <script src="https://kit.fontawesome.com/c497ad14fd.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</head>

<body class="letra">
<div class="formulario">
<br>
<h2 align="center">Nueva Conversacion</h2>

    <%= form_tag conversaciones_path, method: :post do %>
        <div>
            <label>Para:&nbsp;&nbsp;<i class="fa-regular fa-user"></i></label>
            <%= select_tag :user_id, options_from_collection_for_select(@usuarios, :id, :name) %>
        </div>

        <div class="username">
            <%= text_field_tag :subject, nil, placeholder: "Asunto" %>
        </div>

        <div class="username">
            <%= text_area_tag :body, nil, placeholder: "Deje un comentario" %>
        </div>

        <%= submit_tag %>
    <% end %>
    <br>
</div>
</body>

app/views/conversaciones/show.html.erb
<header>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500&display=swap" rel="stylesheet">
</header>

  <body class="letra">
    <section class="h-screen flex overflow-auto">
      <div class="bg-white w-full p-6">
        <h3 class="text-2xl mb-8">Chat en linea</h3>
      <div class="bg-gray-100 w-9/12">
        <div class="py-6 px-20 overflow-auto h-3/4">
          <% @conversacion.receipts_for(current_user).each do |receipt| %>  
            <% if receipt.message.sender.name == current_user.name %>
              <div class="flex mb-12 flex-row-reverse">
                <img src="<%= asset_path 'usuarios.png' %>" class=" self-end rounded-full w-12 mr-4">
                <div class="flex-col">
                  <div class="bg-blue-500 p-6 w-96 rounded-3xl rounded-br-none shadow-sm mb-2">
                    <p class="mb-1 text-white"><%= receipt.message.sender.name %></p>
                    <small class="text-white font-light"><%= receipt.message.body %></small>
                  </div>
                </div>
              </div>
            <% else %>
              <div class="flex mb-12">
                <img src="<%= asset_path 'usuarios.png' %>" class=" self-end rounded-full w-12 mr-4">
                <div class="flex-col">
                  <div class="bg-white p-6 w-96 rounded-3xl rounded-bl-none shadow-sm mb-2">
                    <p class="mb-1"><%= receipt.message.sender.name %></p>
                    <small class="text-gray-500 font-light"><%= receipt.message.body %></small>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <%= form_tag conversacione_mensajes_path(@conversacion), method: :post do %>
          <div class="py-6 px-20 flex border-t">
            <%=  text_area_tag :body %>
            <!-- <input type="" class="px-4 py-2 bg-gray-100 w-full focus:outline-none font-light" placeholder="Escribe tu mensaje..."> -->
            <%=  submit_tag %>
          </div>
        <% end %>
      </div>
    </section>
  </body>